# Configure main menu and social menu
[[main]]
identifier = "auth"
name = "登录"
url = "https://auth.summonhim.top:8443/"
weight = 100
[main.params]
icon = "login-2"
newtab = true



[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/SummonHIM"
[social.params]
icon = "brand-github"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/SummonHIM"
[social.params]
icon = "brand-telegram"

[[social]]
identifier = "bilibili"
name = "BiliBili"
url = "https://space.bilibili.com/21899295"
[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "steam"
name = "Steam"
url = "https://steamcommunity.com/id/SummonHIM"
[social.params]
icon = "brand-steam"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/SummonHIMs"
[social.params]
icon = "brand-twitter"

[[social]]
identifier = "email"
name = "E-Mail"
url = "mailto:summonhim@qq.com"
[social.params]
icon = "mail"
