# SITE CONFIGURATION
baseurl: ""
url: "https://summonhim.top"

# THEME-SPECIFIC CONFIGURATION
title: SummonHIM's Logs                                 # site's title
description: "Log for SummonHIM"                        # used by search engines
avatar: https://avatars.githubusercontent.com/u/33192611?v=4 # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: SummonHIM's Logs                           # Change Blog header text
header_feature_image: http://www.dmoe.cc/random.php
header_feature_image_responsive: true
footer_text: >
  Powered by <a target="_blank" href="https://jekyllrb.com/">Jekyll</a> with <a target="_blank" href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a><br>© 2022 <a href="https://summonhim.top/">8-Bits Group</a>
chn_website_approve: false
chn_website_approve_region: "粤"
chn_website_approve_icp: 2021004741
chn_website_approve_police: 44040202001263

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id: adaf6c7e-8ca3-4335-aeb1-e04b20102f11   # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*", ".vscode/*", "autosync.sh"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
